-- MySQL Script generated by MySQL Workbench
-- Tue Mar 21 22:09:08 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema letadlo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema letadlo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `letadlo` DEFAULT CHARACTER SET utf8 ;
USE `letadlo` ;

-- -----------------------------------------------------
-- Table `letadlo`.`flight`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `letadlo`.`flight` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `where` VARCHAR(255) NOT NULL,
  `to` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `letadlo`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `letadlo`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `surname` VARCHAR(255) NOT NULL,
  `fly_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_fly_idx` (`fly_id` ASC),
  CONSTRAINT `fk_user_fly`
    FOREIGN KEY (`fly_id`)
    REFERENCES `letadlo`.`flight` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
